name: Livestream

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest

    steps:
      - name: Install FFmpeg and yt-dlp
        run: |
          sudo apt update
          sudo apt install ffmpeg -y
          pip install yt-dlp

      - name: Download Video
  run: |
    yt-dlp -f "bv*+ba/b" https://www.youtube.com/watch?v=Zyd1iug_Ay4 -o video.mp4

- name: Stream to YouTube
  run: |
    ffmpeg -re -stream_loop -1 -i video.mp4 -t 18000 -c:v libx264 -preset veryfast -b:v 1500k -c:a aac -b:a 128k -f flv rtmp://a.rtmp.youtube.com/live2/YOUR-STREAM-KEY
